"""Baseline: interpreters, meetings, bookings, assignments, invoices and the log

Revision ID: 0001
Revises: 
Create Date: 2026-10-10 23:20:18.737868
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interpreters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('bureau_affiliation', sa.String(length=200), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('additional_languages', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('engagement', sa.String(length=20), server_default='invoice', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("engagement IN ('invoice', 'occasional_work')", name='ck_interpreters_engagement'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('interpreters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interpreters_priority_order'), ['priority_order'], unique=False)

    op.create_table('meeting_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('change_number', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.String(length=200), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('new', 'changed', 'cancelled', 'reopened', 'deleted', 'restored', 'moved', 'week_status', 'edited')", name='ck_meeting_changes_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_changes_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_changes_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('rooms',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_change_number', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_full_comparison_at', sa.DateTime(), nullable=True),
    sa.Column('spic_highest_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.CheckConstraint('start_time < end_time', name='ck_time_slots_order'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_slots_date'), ['date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interpreter_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('booking_reason', sa.String(length=200), nullable=True),
    sa.Column('forfait_hours', sa.Integer(), server_default='4', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("forfait_hours IN ('3', '4')", name='ck_bookings_forfait'),
    sa.CheckConstraint("status IN ('proposed', 'confirmed', 'completed', 'cancelled')", name='ck_bookings_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreters.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['time_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_interpreter_id'), ['interpreter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_slot_id'), ['slot_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interpreter_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.Column('checked_on', sa.Date(), nullable=True),
    sa.Column('checked_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_interpreter_id'), ['interpreter_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=5), nullable=False),
    sa.Column('spic_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('week', sa.Date(), nullable=True),
    sa.Column('week_status', sa.String(length=15), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=2), nullable=False),
    sa.Column('start_kind', sa.String(length=5), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('effective_start', sa.Time(), nullable=True),
    sa.Column('expected_end', sa.Time(), nullable=True),
    sa.Column('end_next_day', sa.Boolean(), nullable=False),
    sa.Column('room', sa.String(length=20), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('assembly', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('sequence_number_2', sa.Integer(), nullable=True),
    sa.Column('interpreters_needed', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actual_end', sa.Time(), nullable=True),
    sa.Column('charged_half_hours', sa.Integer(), nullable=True),
    sa.Column('spic_data', sa.JSON(), nullable=True),
    sa.Column('spic_version', sa.Integer(), nullable=True),
    sa.Column('last_change_number', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_in_spic_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("(origin = 'spic' AND spic_id IS NOT NULL) OR (origin = 'own' AND spic_id IS NULL AND title IS NOT NULL AND room IS NOT NULL AND category IS NOT NULL AND interpreters_needed IS NOT NULL)", name='ck_meetings_origin_fields'),
    sa.CheckConstraint("origin IN ('spic', 'own')", name='ck_meetings_origin'),
    sa.CheckConstraint("period IN ('AM', 'PM')", name='ck_meetings_period'),
    sa.CheckConstraint("start_kind IS NULL OR start_kind IN ('time', 'after')", name='ck_meetings_start_kind'),
    sa.CheckConstraint("status <> 'deleted' OR origin = 'spic'", name='ck_meetings_deleted_is_spic'),
    sa.CheckConstraint("status IN ('planned', 'cancelled', 'deleted')", name='ck_meetings_status'),
    sa.CheckConstraint("week_status IS NULL OR week_status IN ('pre_definitive', 'definitive', 'concept')", name='ck_meetings_week_status'),
    sa.CheckConstraint('charged_half_hours IS NULL OR charged_half_hours >= 0', name='ck_meetings_charged'),
    sa.CheckConstraint('interpreters_needed IS NULL OR interpreters_needed > 0', name='ck_meetings_needed'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spic_id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_date'), ['date'], unique=False)

    op.create_table('user_visits',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('booking_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('interpreter_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('dimona_declared', sa.Boolean(), server_default='0', nullable=False),
    sa.CheckConstraint("status IN ('active', 'cancelled')", name='ck_positions_status'),
    sa.CheckConstraint('actual_end_time IS NULL OR actual_start_time IS NULL OR actual_end_time > actual_start_time', name='ck_positions_hours'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'position_number', name='uq_positions_number')
    )
    with op.batch_alter_table('booking_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_positions_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_positions_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('meeting_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_communicated_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('proposed', 'confirmed', 'cancelled')", name='ck_assignments_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['booking_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'meeting_id', name='uq_assignments_position_meeting')
    )
    with op.batch_alter_table('meeting_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_assignments_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_assignments_position_id'), ['position_id'], unique=False)

    op.create_table('assignment_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.Column('interpreter_name', sa.String(length=200), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('meeting_snapshot', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['meeting_assignments.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreters.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['booking_positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_log_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_log_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_log_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_log_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_log_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###

    # The log and the history are append-only: the database itself refuses to change or remove a line.
    for table in ("assignment_log", "meeting_changes"):
        for verb in ("UPDATE", "DELETE"):
            op.execute(
                "CREATE TRIGGER {t}_no_{v} BEFORE {V} ON {t} "
                "BEGIN SELECT RAISE(ABORT, '{t} is append-only'); END".format(t=table, v=verb.lower(), V=verb)
            )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_log_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_assignment_log_position_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_log_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_log_booking_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_log_assignment_id'))

    op.drop_table('assignment_log')
    with op.batch_alter_table('meeting_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_assignments_position_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_assignments_meeting_id'))

    op.drop_table('meeting_assignments')
    with op.batch_alter_table('booking_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_positions_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_booking_positions_booking_id'))

    op.drop_table('booking_positions')
    op.drop_table('user_visits')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_date'))

    op.drop_table('meetings')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_interpreter_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_slot_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_interpreter_id'))

    op.drop_table('bookings')
    op.drop_table('users')
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_slots_date'))

    op.drop_table('time_slots')
    op.drop_table('sync_state')
    op.drop_table('rooms')
    with op.batch_alter_table('meeting_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_changes_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_meeting_changes_meeting_id'))

    op.drop_table('meeting_changes')
    with op.batch_alter_table('interpreters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interpreters_priority_order'))

    op.drop_table('interpreters')
    # ### end Alembic commands ###
